version: '3'

services:
  app-elasticsearch:
    container_name: stac-fastapi-es
    image: stac-utils/stac-fastapi
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    platform: linux/amd64
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8083
      - RELOAD=false
      - ENVIRONMENT=local
      - WEB_CONCURRENCY=10
      - ES_USER=dev
      - ES_PASS=stac
      - ES_PORT=9200
      - ES_HOST=172.17.0.1
    ports:
      - "8083:8083"
    volumes:
      - ./stac_fastapi:/app/stac_fastapi
      - ./scripts:/app/scripts
    depends_on:
      - elasticsearch
    command:
      bash -c "./scripts/wait-for-it.sh es-container:9200 && python -m stac_fastapi.elasticsearch.app"

  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200

networks:
  default:
    name: stac-fastapi-network
