version: '3'

services:
  docs:
    container_name: stac-fastapi-docs-dev
    build:
      context: .
      dockerfile: Dockerfile.docs
    platform: linux/amd64
    environment:
    - STAC_FASTAPI_TITLE=stac-fastapi-opensearch
    - STAC_FASTAPI_DESCRIPTION=A STAC FastAPI with an Opensearch backend
    - STAC_FASTAPI_VERSION=2.1
    - APP_HOST=0.0.0.0
    - APP_PORT=8082
    - RELOAD=true
    - ENVIRONMENT=local
    - WEB_CONCURRENCY=10
    - ES_HOST=opensearch
    - ES_PORT=9202
    - ES_USE_SSL=false
    - ES_VERIFY_CERTS=false
    - BACKEND=opensearch
    volumes:
      - .:/opt/src