name: stac-fastapi-nosql
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      mongo_db_service:
        image: mongo:3.6
        env:
          MONGO_INITDB_ROOT_USERNAME: dev
          MONGO_INITDB_ROOT_PASSWORD: stac
        ports:
          - 27018:27017

      elasticsearch_db_service:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
        env:
          "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
          - 9200:9200
      
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Lint code
        uses: pre-commit/action@v2.0.0

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Install mongo stac-fastapi
        run: |
          pip install ./stac_fastapi/mongo[dev,server]

      - name: Install elasticsearch stac-fastapi
        run: |
          pip install ./stac_fastapi/elasticsearch[dev,server]

      - name: Run test suite
        run: |
          cd stac_fastapi/mongo && pipenv run pytest -svvv
        env:
          ENVIRONMENT: testing
          # POSTGRES_USER: username
          # POSTGRES_PASS: password
          # POSTGRES_DBNAME: postgis
          # POSTGRES_HOST_READER: localhost
          # POSTGRES_HOST_WRITER: localhost
          # POSTGRES_PORT: 5432
          MONGO_USER: dev
          MONGO_PASS: stac
          MONGO_PORT: 27018
          MONGO_HOST: localhost
      
      - name: Run test suite
        run: |
          cd stac_fastapi/elasticsearch && pipenv run pytest -svvv
        env:
          ENVIRONMENT: testing
          ES_USER: dev
          ES_PASS: stac
          ES_PORT: 9200
          ES_HOST: 172.17.0.1
          
  # test-docs:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Test generating docs
  #       run: make docs