name: stac-fastapi-elasticsearch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - features/**

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:

      elasticsearch_8_svc:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3
        env:
          ES_JAVA_OPTS: -Xms512m -Xmx1g
        options: -v ${{ github.workspace }}/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        ports:
          - 9200:9200

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Lint code
        uses: pre-commit/action@v2.0.3

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Install elasticsearch stac-fastapi
        run: |
          pip install ./stac_fastapi/elasticsearch[dev,server]

      - name: Run test suite against Elasticsearch 8.x
        run: |
          cd stac_fastapi/elasticsearch && pipenv run pytest -svvv
        env:
          ENVIRONMENT: testing
          ES_PORT: 9200
          ES_HOST: 172.17.0.1
          ES_USE_SSL: false
          ES_VERIFY_CERTS: false