name: Publish docs via GitHub Pages

on:
  pull_request:
    branches:
      - main
    paths:
      # Rebuild website when docs have changed or code has changed
      - "README.md"
      - "docs/**"
      - "**.py"
  workflow_dispatch:

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install \
            stac_fastapi/core \
            stac_fastapi/elasticsearch[docs] \
            stac_fastapi/opensearch \

      - name: update API docs
        run: |
          pdocs as_markdown \
            --output_dir docs/src/api/ \
            --exclude_source \
            --overwrite \
            stac_fastapi
        env:
          APP_HOST: 0.0.0.0
          APP_PORT: 8082
          ES_HOST: opensearch
          ES_PORT: 9202
          ES_USE_SSL: false
          ES_VERIFY_CERTS: false
          BACKEND: opensearch

      - name: Deploy docs
        run: mkdocs gh-deploy --force -f docs/mkdocs.yml